// <auto-generated />
using System;
using Arosaje_KSENV.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arosaje_KSENV.Migrations
{
    [DbContext(typeof(ArosajeKsenvContext))]
    partial class ArosajeKsenvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arosaje_KSENV.Models.Botaniste", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Botanist__63A5C1FFBCC7A728");

                    b.ToTable("Botaniste", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.DateTip", b =>
                {
                    b.Property<int>("IdTips")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Tips");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTips"));

                    b.Property<string>("Contenu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contenu");

                    b.HasKey("IdTips")
                        .HasName("PK__dateTips__0641639EAF8D1B48");

                    b.ToTable("dateTips", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.EnvoyerRecevoir", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.Property<int>("IdUtilisateur1")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur_1");

                    b.Property<int>("IdUtilisateur2")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur_2");

                    b.Property<int>("IdMessage")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Message");

                    b.HasKey("IdUtilisateur", "IdUtilisateur1", "IdUtilisateur2", "IdMessage")
                        .HasName("PK__Envoyer___97E4F897273813C5");

                    b.HasIndex("IdMessage");

                    b.HasIndex("IdUtilisateur1");

                    b.HasIndex("IdUtilisateur2");

                    b.ToTable("Envoyer_recevoir", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Membre", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Membre__63A5C1FFA80227E1");

                    b.ToTable("Membre", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Message");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMessage"));

                    b.Property<string>("Contenu")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contenu");

                    b.Property<DateTime?>("DateMessage")
                        .HasColumnType("date")
                        .HasColumnName("dateMessage");

                    b.HasKey("IdMessage")
                        .HasName("PK__Message__A33138E696D85CD1");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Photo", b =>
                {
                    b.Property<int>("IdPhoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Photo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPhoto"));

                    b.Property<string>("Image")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("image");

                    b.Property<string>("extension")
                        .HasColumnType("text");

                    b.HasKey("IdPhoto")
                        .HasName("PK__Photo__96CEBB73EF77EAA1");

                    b.ToTable("Photo", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Plante", b =>
                {
                    b.Property<int>("IdPlante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Plante");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlante"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Espece")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Etat")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("IdPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Photo");

                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.Property<int?>("IdUtilisateur1")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur_1");

                    b.Property<int>("IdVille")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Ville");

                    b.Property<string>("Lat")
                        .HasColumnType("text");

                    b.Property<string>("Lon")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdPlante")
                        .HasName("PK__Plante__8E9A9EE58E900046");

                    b.HasIndex("IdPhoto");

                    b.HasIndex("IdUtilisateur");

                    b.HasIndex("IdUtilisateur1");

                    b.HasIndex("IdVille");

                    b.ToTable("Plante", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Proprio", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Proprio__63A5C1FFDE3A6090");

                    b.ToTable("Proprio", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Utilisateur", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUtilisateur"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mdp")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUtilisateur")
                        .HasName("PK__Utilisat__63A5C1FF9ADAA4AE");

                    b.ToTable("Utilisateur", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Ville", b =>
                {
                    b.Property<int>("IdVille")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id_Ville");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVille"));

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdVille")
                        .HasName("PK__Ville__EF0C38FCB16C0CA0");

                    b.ToTable("Ville", (string)null);
                });

            modelBuilder.Entity("Conseiller", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.Property<int>("IdTips")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Tips");

                    b.HasKey("IdUtilisateur", "IdTips")
                        .HasName("PK__Conseill__93C1D7C6ECFA37EC");

                    b.HasIndex("IdTips");

                    b.ToTable("Conseiller", (string)null);
                });

            modelBuilder.Entity("Habite", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.Property<int>("IdVille")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Ville");

                    b.HasKey("IdUtilisateur", "IdVille")
                        .HasName("PK__Habite__BD550270470E1D44");

                    b.HasIndex("IdVille");

                    b.ToTable("Habite", (string)null);
                });

            modelBuilder.Entity("HasTip", b =>
                {
                    b.Property<int>("IdPlante")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Plante");

                    b.Property<int>("IdTips")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Tips");

                    b.HasKey("IdPlante", "IdTips")
                        .HasName("PK__HasTips__7EFE88DC09331A83");

                    b.HasIndex("IdTips");

                    b.ToTable("HasTips", (string)null);
                });

            modelBuilder.Entity("Prendre", b =>
                {
                    b.Property<int>("IdUtilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Utilisateur");

                    b.Property<int>("IdPhoto")
                        .HasColumnType("integer")
                        .HasColumnName("Id_Photo");

                    b.HasKey("IdUtilisateur", "IdPhoto")
                        .HasName("PK__Prendre__4AC92A48BE6E6FB2");

                    b.HasIndex("IdPhoto");

                    b.ToTable("Prendre", (string)null);
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Botaniste", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Botaniste")
                        .HasForeignKey("Arosaje_KSENV.Models.Botaniste", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Botaniste__Id_Ut__3C69FB99");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.EnvoyerRecevoir", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Message", "IdMessageNavigation")
                        .WithMany("EnvoyerRecevoirs")
                        .HasForeignKey("IdMessage")
                        .IsRequired()
                        .HasConstraintName("FK__Envoyer_r__Id_Me__5629CD9C");

                    b.HasOne("Arosaje_KSENV.Models.Membre", "IdUtilisateurNavigation")
                        .WithMany("EnvoyerRecevoirs")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Envoyer_r__Id_Ut__534D60F1");

                    b.HasOne("Arosaje_KSENV.Models.Botaniste", "IdUtilisateur1Navigation")
                        .WithMany("EnvoyerRecevoirs")
                        .HasForeignKey("IdUtilisateur1")
                        .IsRequired()
                        .HasConstraintName("FK__Envoyer_r__Id_Ut__5441852A");

                    b.HasOne("Arosaje_KSENV.Models.Proprio", "IdUtilisateur2Navigation")
                        .WithMany("EnvoyerRecevoirs")
                        .HasForeignKey("IdUtilisateur2")
                        .IsRequired()
                        .HasConstraintName("FK__Envoyer_r__Id_Ut__5535A963");

                    b.Navigation("IdMessageNavigation");

                    b.Navigation("IdUtilisateur1Navigation");

                    b.Navigation("IdUtilisateur2Navigation");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Membre", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Membre")
                        .HasForeignKey("Arosaje_KSENV.Models.Membre", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Membre__Id_Utili__398D8EEE");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Plante", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Photo", "IdPhotoNavigation")
                        .WithMany("Plantes")
                        .HasForeignKey("IdPhoto")
                        .HasConstraintName("FK__Plante__Id_Photo__4AB81AF0");

                    b.HasOne("Arosaje_KSENV.Models.Membre", "IdUtilisateurNavigation")
                        .WithMany("PlanteIdUtilisateurNavigations")
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Plante__Id_Utili__4BAC3F29");

                    b.HasOne("Arosaje_KSENV.Models.Membre", "IdUtilisateur1Navigation")
                        .WithMany("PlanteIdUtilisateur1Navigations")
                        .HasForeignKey("IdUtilisateur1")
                        .HasConstraintName("FK__Plante__Id_Utili__4CA06362");

                    b.HasOne("Arosaje_KSENV.Models.Ville", "IdVilleNavigation")
                        .WithMany("Plantes")
                        .HasForeignKey("IdVille")
                        .IsRequired()
                        .HasConstraintName("FK__Plante__Id_Ville__49C3F6B7");

                    b.Navigation("IdPhotoNavigation");

                    b.Navigation("IdUtilisateur1Navigation");

                    b.Navigation("IdUtilisateurNavigation");

                    b.Navigation("IdVilleNavigation");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Proprio", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Utilisateur", "IdUtilisateurNavigation")
                        .WithOne("Proprio")
                        .HasForeignKey("Arosaje_KSENV.Models.Proprio", "IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Proprio__Id_Util__46E78A0C");

                    b.Navigation("IdUtilisateurNavigation");
                });

            modelBuilder.Entity("Conseiller", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.DateTip", null)
                        .WithMany()
                        .HasForeignKey("IdTips")
                        .IsRequired()
                        .HasConstraintName("FK__Conseille__Id_Ti__59FA5E80");

                    b.HasOne("Arosaje_KSENV.Models.Botaniste", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Conseille__Id_Ut__59063A47");
                });

            modelBuilder.Entity("Habite", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Habite__Id_Utili__60A75C0F");

                    b.HasOne("Arosaje_KSENV.Models.Ville", null)
                        .WithMany()
                        .HasForeignKey("IdVille")
                        .IsRequired()
                        .HasConstraintName("FK__Habite__Id_Ville__619B8048");
                });

            modelBuilder.Entity("HasTip", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Plante", null)
                        .WithMany()
                        .HasForeignKey("IdPlante")
                        .IsRequired()
                        .HasConstraintName("FK__HasTips__Id_Plan__5CD6CB2B");

                    b.HasOne("Arosaje_KSENV.Models.DateTip", null)
                        .WithMany()
                        .HasForeignKey("IdTips")
                        .IsRequired()
                        .HasConstraintName("FK__HasTips__Id_Tips__5DCAEF64");
                });

            modelBuilder.Entity("Prendre", b =>
                {
                    b.HasOne("Arosaje_KSENV.Models.Photo", null)
                        .WithMany()
                        .HasForeignKey("IdPhoto")
                        .IsRequired()
                        .HasConstraintName("FK__Prendre__Id_Phot__5070F446");

                    b.HasOne("Arosaje_KSENV.Models.Membre", null)
                        .WithMany()
                        .HasForeignKey("IdUtilisateur")
                        .IsRequired()
                        .HasConstraintName("FK__Prendre__Id_Util__4F7CD00D");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Botaniste", b =>
                {
                    b.Navigation("EnvoyerRecevoirs");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Membre", b =>
                {
                    b.Navigation("EnvoyerRecevoirs");

                    b.Navigation("PlanteIdUtilisateur1Navigations");

                    b.Navigation("PlanteIdUtilisateurNavigations");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Message", b =>
                {
                    b.Navigation("EnvoyerRecevoirs");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Photo", b =>
                {
                    b.Navigation("Plantes");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Proprio", b =>
                {
                    b.Navigation("EnvoyerRecevoirs");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Utilisateur", b =>
                {
                    b.Navigation("Botaniste");

                    b.Navigation("Membre");

                    b.Navigation("Proprio");
                });

            modelBuilder.Entity("Arosaje_KSENV.Models.Ville", b =>
                {
                    b.Navigation("Plantes");
                });
#pragma warning restore 612, 618
        }
    }
}
